name: CI Cache Speedup
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/dummy-cache
          key: cache-e64fe29

      - name: prime-cache-e64fe29
        run: echo "Cache hit/miss result: ${{ steps.cache-step.outputs.cache-hit }}"

      - name: Create dummy file for caching
        run: |
          mkdir -p ~/dummy-cache
          echo "This is a cached file" > ~/dummy-cache/data.txt
